//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.08 at 11:52:04 AM CET 
//


package nl.nn.dcdc.api.bpxsd;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for EmployeeDisabilityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmployeeDisabilityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DisabilityClass" type="{http://www.w3.org/2001/XMLSchema}ID" minOccurs="0"/>
 *         &lt;element name="DisabilityStart" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="DisabilityEnd" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="DisabilityPercentage" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}percentage" minOccurs="0"/>
 *         &lt;element name="ActualPercentage" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}percentage" minOccurs="0"/>
 *         &lt;element name="CompanyPercentage" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}percentage" minOccurs="0"/>
 *         &lt;element name="WAOPercentage" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}percentage" minOccurs="0"/>
 *         &lt;element name="WIAPercentage" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}percentage" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmployeeDisabilityType", propOrder = {
    "disabilityClass",
    "disabilityStart",
    "disabilityEnd",
    "disabilityPercentage",
    "actualPercentage",
    "companyPercentage",
    "waoPercentage",
    "wiaPercentage"
})
public class EmployeeDisabilityType {

    @XmlElement(name = "DisabilityClass")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String disabilityClass;
    @XmlElement(name = "DisabilityStart")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar disabilityStart;
    @XmlElement(name = "DisabilityEnd")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar disabilityEnd;
    @XmlElement(name = "DisabilityPercentage")
    protected BigDecimal disabilityPercentage;
    @XmlElement(name = "ActualPercentage")
    protected BigDecimal actualPercentage;
    @XmlElement(name = "CompanyPercentage")
    protected BigDecimal companyPercentage;
    @XmlElement(name = "WAOPercentage")
    protected BigDecimal waoPercentage;
    @XmlElement(name = "WIAPercentage")
    protected BigDecimal wiaPercentage;

    /**
     * Gets the value of the disabilityClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisabilityClass() {
        return disabilityClass;
    }

    /**
     * Sets the value of the disabilityClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisabilityClass(String value) {
        this.disabilityClass = value;
    }

    /**
     * Gets the value of the disabilityStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDisabilityStart() {
        return disabilityStart;
    }

    /**
     * Sets the value of the disabilityStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDisabilityStart(XMLGregorianCalendar value) {
        this.disabilityStart = value;
    }

    /**
     * Gets the value of the disabilityEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDisabilityEnd() {
        return disabilityEnd;
    }

    /**
     * Sets the value of the disabilityEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDisabilityEnd(XMLGregorianCalendar value) {
        this.disabilityEnd = value;
    }

    /**
     * Gets the value of the disabilityPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDisabilityPercentage() {
        return disabilityPercentage;
    }

    /**
     * Sets the value of the disabilityPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDisabilityPercentage(BigDecimal value) {
        this.disabilityPercentage = value;
    }

    /**
     * Gets the value of the actualPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getActualPercentage() {
        return actualPercentage;
    }

    /**
     * Sets the value of the actualPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setActualPercentage(BigDecimal value) {
        this.actualPercentage = value;
    }

    /**
     * Gets the value of the companyPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCompanyPercentage() {
        return companyPercentage;
    }

    /**
     * Sets the value of the companyPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCompanyPercentage(BigDecimal value) {
        this.companyPercentage = value;
    }

    /**
     * Gets the value of the waoPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWAOPercentage() {
        return waoPercentage;
    }

    /**
     * Sets the value of the waoPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWAOPercentage(BigDecimal value) {
        this.waoPercentage = value;
    }

    /**
     * Gets the value of the wiaPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWIAPercentage() {
        return wiaPercentage;
    }

    /**
     * Sets the value of the wiaPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWIAPercentage(BigDecimal value) {
        this.wiaPercentage = value;
    }

}
