//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.08 at 11:52:04 AM CET 
//


package nl.nn.dcdc.api.bpxsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for FatcaCRSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FatcaCRSType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TaxCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TaxPayer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TaxNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DueDiligenceStart" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="DueDiligenceEnd" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ChangedCircumstancesStart" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FatcaCRSType", propOrder = {
    "taxCountry",
    "taxPayer",
    "taxNumber",
    "dueDiligenceStart",
    "dueDiligenceEnd",
    "changedCircumstancesStart"
})
public class FatcaCRSType {

    @XmlElement(name = "TaxCountry", required = true)
    protected String taxCountry;
    @XmlElement(name = "TaxPayer")
    protected String taxPayer;
    @XmlElement(name = "TaxNumber")
    protected String taxNumber;
    @XmlElement(name = "DueDiligenceStart")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dueDiligenceStart;
    @XmlElement(name = "DueDiligenceEnd")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dueDiligenceEnd;
    @XmlElement(name = "ChangedCircumstancesStart")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar changedCircumstancesStart;

    /**
     * Gets the value of the taxCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxCountry() {
        return taxCountry;
    }

    /**
     * Sets the value of the taxCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxCountry(String value) {
        this.taxCountry = value;
    }

    /**
     * Gets the value of the taxPayer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxPayer() {
        return taxPayer;
    }

    /**
     * Sets the value of the taxPayer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxPayer(String value) {
        this.taxPayer = value;
    }

    /**
     * Gets the value of the taxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxNumber() {
        return taxNumber;
    }

    /**
     * Sets the value of the taxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxNumber(String value) {
        this.taxNumber = value;
    }

    /**
     * Gets the value of the dueDiligenceStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueDiligenceStart() {
        return dueDiligenceStart;
    }

    /**
     * Sets the value of the dueDiligenceStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueDiligenceStart(XMLGregorianCalendar value) {
        this.dueDiligenceStart = value;
    }

    /**
     * Gets the value of the dueDiligenceEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueDiligenceEnd() {
        return dueDiligenceEnd;
    }

    /**
     * Sets the value of the dueDiligenceEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueDiligenceEnd(XMLGregorianCalendar value) {
        this.dueDiligenceEnd = value;
    }

    /**
     * Gets the value of the changedCircumstancesStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getChangedCircumstancesStart() {
        return changedCircumstancesStart;
    }

    /**
     * Sets the value of the changedCircumstancesStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setChangedCircumstancesStart(XMLGregorianCalendar value) {
        this.changedCircumstancesStart = value;
    }

}
