//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.08 at 11:52:04 AM CET 
//


package nl.nn.dcdc.api.bpxsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HandleBusinessPartner_RequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HandleBusinessPartner_RequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequestEnvelope" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}RequestEnvelopeType"/>
 *         &lt;element name="Party" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}PartyType" minOccurs="0"/>
 *         &lt;element name="Employer" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}EmployerType" minOccurs="0"/>
 *         &lt;element name="Employee" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}EmployeeType" minOccurs="0"/>
 *         &lt;element name="BankDetails" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}BankDetailsType" minOccurs="0"/>
 *         &lt;element name="LongTexts" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}LongTextsType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HandleBusinessPartner_RequestType", propOrder = {
    "requestEnvelope",
    "party",
    "employer",
    "employee",
    "bankDetails",
    "longTexts"
})
public class HandleBusinessPartnerRequestType {

    @XmlElement(name = "RequestEnvelope", required = true)
    protected RequestEnvelopeType requestEnvelope;
    @XmlElement(name = "Party")
    protected PartyType party;
    @XmlElement(name = "Employer")
    protected EmployerType employer;
    @XmlElement(name = "Employee")
    protected EmployeeType employee;
    @XmlElement(name = "BankDetails")
    protected BankDetailsType bankDetails;
    @XmlElement(name = "LongTexts")
    protected List<LongTextsType> longTexts;

    /**
     * Gets the value of the requestEnvelope property.
     * 
     * @return
     *     possible object is
     *     {@link RequestEnvelopeType }
     *     
     */
    public RequestEnvelopeType getRequestEnvelope() {
        return requestEnvelope;
    }

    /**
     * Sets the value of the requestEnvelope property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestEnvelopeType }
     *     
     */
    public void setRequestEnvelope(RequestEnvelopeType value) {
        this.requestEnvelope = value;
    }

    /**
     * Gets the value of the party property.
     * 
     * @return
     *     possible object is
     *     {@link PartyType }
     *     
     */
    public PartyType getParty() {
        return party;
    }

    /**
     * Sets the value of the party property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyType }
     *     
     */
    public void setParty(PartyType value) {
        this.party = value;
    }

    /**
     * Gets the value of the employer property.
     * 
     * @return
     *     possible object is
     *     {@link EmployerType }
     *     
     */
    public EmployerType getEmployer() {
        return employer;
    }

    /**
     * Sets the value of the employer property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployerType }
     *     
     */
    public void setEmployer(EmployerType value) {
        this.employer = value;
    }

    /**
     * Gets the value of the employee property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeeType }
     *     
     */
    public EmployeeType getEmployee() {
        return employee;
    }

    /**
     * Sets the value of the employee property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeeType }
     *     
     */
    public void setEmployee(EmployeeType value) {
        this.employee = value;
    }

    /**
     * Gets the value of the bankDetails property.
     * 
     * @return
     *     possible object is
     *     {@link BankDetailsType }
     *     
     */
    public BankDetailsType getBankDetails() {
        return bankDetails;
    }

    /**
     * Sets the value of the bankDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankDetailsType }
     *     
     */
    public void setBankDetails(BankDetailsType value) {
        this.bankDetails = value;
    }

    /**
     * Gets the value of the longTexts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the longTexts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLongTexts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LongTextsType }
     * 
     * 
     */
    public List<LongTextsType> getLongTexts() {
        if (longTexts == null) {
            longTexts = new ArrayList<LongTextsType>();
        }
        return this.longTexts;
    }

}
