//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.08 at 11:52:04 AM CET 
//


package nl.nn.dcdc.api.bpxsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="From" type="{http://nn.nl/XSD/Generic/MessageHeader/2}ProducingEndpointType"/>
 *         &lt;element name="To" type="{http://nn.nl/XSD/Generic/MessageHeader/2}ConsumingEndpointType"/>
 *         &lt;element name="HeaderFields" type="{http://nn.nl/XSD/Generic/MessageHeader/2}HeaderFieldType"/>
 *         &lt;element name="ConnectionInfo" type="{http://nn.nl/XSD/Generic/MessageHeader/2}ConnectionInfoType" minOccurs="0"/>
 *         &lt;element name="Service" type="{http://nn.nl/XSD/Generic/MessageHeader/2}ServiceType"/>
 *         &lt;element name="TraceHeaderList" type="{http://nn.nl/XSD/Generic/MessageHeader/2}TraceHeaderListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageHeaderType", namespace = "http://nn.nl/XSD/Generic/MessageHeader/2", propOrder = {
    "from",
    "to",
    "headerFields",
    "connectionInfo",
    "service",
    "traceHeaderList"
})
public class MessageHeaderType {

    @XmlElement(name = "From", required = true)
    protected ProducingEndpointType from;
    @XmlElement(name = "To", required = true)
    protected ConsumingEndpointType to;
    @XmlElement(name = "HeaderFields", required = true)
    protected HeaderFieldType headerFields;
    @XmlElement(name = "ConnectionInfo")
    protected ConnectionInfoType connectionInfo;
    @XmlElement(name = "Service", required = true)
    protected ServiceType service;
    @XmlElement(name = "TraceHeaderList")
    protected TraceHeaderListType traceHeaderList;

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link ProducingEndpointType }
     *     
     */
    public ProducingEndpointType getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProducingEndpointType }
     *     
     */
    public void setFrom(ProducingEndpointType value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link ConsumingEndpointType }
     *     
     */
    public ConsumingEndpointType getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsumingEndpointType }
     *     
     */
    public void setTo(ConsumingEndpointType value) {
        this.to = value;
    }

    /**
     * Gets the value of the headerFields property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderFieldType }
     *     
     */
    public HeaderFieldType getHeaderFields() {
        return headerFields;
    }

    /**
     * Sets the value of the headerFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderFieldType }
     *     
     */
    public void setHeaderFields(HeaderFieldType value) {
        this.headerFields = value;
    }

    /**
     * Gets the value of the connectionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionInfoType }
     *     
     */
    public ConnectionInfoType getConnectionInfo() {
        return connectionInfo;
    }

    /**
     * Sets the value of the connectionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionInfoType }
     *     
     */
    public void setConnectionInfo(ConnectionInfoType value) {
        this.connectionInfo = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceType }
     *     
     */
    public ServiceType getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceType }
     *     
     */
    public void setService(ServiceType value) {
        this.service = value;
    }

    /**
     * Gets the value of the traceHeaderList property.
     * 
     * @return
     *     possible object is
     *     {@link TraceHeaderListType }
     *     
     */
    public TraceHeaderListType getTraceHeaderList() {
        return traceHeaderList;
    }

    /**
     * Sets the value of the traceHeaderList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TraceHeaderListType }
     *     
     */
    public void setTraceHeaderList(TraceHeaderListType value) {
        this.traceHeaderList = value;
    }

}
