//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.08 at 11:52:04 AM CET 
//


package nl.nn.dcdc.api.bpxsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MobilePhoneContactPointUsageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MobilePhoneContactPointUsageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ContactPointUsageType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MobilePhoneChangeIND" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MobilePhone" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}MobilePhoneType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MobilePhoneContactPointUsageType", propOrder = {
    "contactPointUsageType",
    "mobilePhoneChangeIND",
    "mobilePhone"
})
public class MobilePhoneContactPointUsageType {

    @XmlElement(name = "ContactPointUsageType")
    protected String contactPointUsageType;
    @XmlElement(name = "MobilePhoneChangeIND")
    protected String mobilePhoneChangeIND;
    @XmlElement(name = "MobilePhone")
    protected MobilePhoneType mobilePhone;

    /**
     * Gets the value of the contactPointUsageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPointUsageType() {
        return contactPointUsageType;
    }

    /**
     * Sets the value of the contactPointUsageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPointUsageType(String value) {
        this.contactPointUsageType = value;
    }

    /**
     * Gets the value of the mobilePhoneChangeIND property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobilePhoneChangeIND() {
        return mobilePhoneChangeIND;
    }

    /**
     * Sets the value of the mobilePhoneChangeIND property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobilePhoneChangeIND(String value) {
        this.mobilePhoneChangeIND = value;
    }

    /**
     * Gets the value of the mobilePhone property.
     * 
     * @return
     *     possible object is
     *     {@link MobilePhoneType }
     *     
     */
    public MobilePhoneType getMobilePhone() {
        return mobilePhone;
    }

    /**
     * Sets the value of the mobilePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link MobilePhoneType }
     *     
     */
    public void setMobilePhone(MobilePhoneType value) {
        this.mobilePhone = value;
    }

}
