//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.08 at 11:52:04 AM CET 
//


package nl.nn.dcdc.api.bpxsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ClassesFromXML package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HandleBusinessPartnerResponse_QNAME = new QName("http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4", "HandleBusinessPartner_Response");
    private final static QName _MessageHeader_QNAME = new QName("http://nn.nl/XSD/Generic/MessageHeader/2", "MessageHeader");
    private final static QName _Result_QNAME = new QName("http://nn.nl/XSD/Generic/MessageHeader/2", "Result");
    private final static QName _HandleBusinessPartnerRequest_QNAME = new QName("http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4", "HandleBusinessPartner_Request");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ClassesFromXML
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PartyType }
     * 
     */
    public PartyType createPartyType() {
        return new PartyType();
    }

    /**
     * Create an instance of {@link BankDetailsType }
     * 
     */
    public BankDetailsType createBankDetailsType() {
        return new BankDetailsType();
    }

    /**
     * Create an instance of {@link HandleBusinessPartnerResponseType }
     * 
     */
    public HandleBusinessPartnerResponseType createHandleBusinessPartnerResponseType() {
        return new HandleBusinessPartnerResponseType();
    }

    /**
     * Create an instance of {@link HandleBusinessPartnerRequestType }
     * 
     */
    public HandleBusinessPartnerRequestType createHandleBusinessPartnerRequestType() {
        return new HandleBusinessPartnerRequestType();
    }

    /**
     * Create an instance of {@link MobilePhoneContactPointUsageType }
     * 
     */
    public MobilePhoneContactPointUsageType createMobilePhoneContactPointUsageType() {
        return new MobilePhoneContactPointUsageType();
    }

    /**
     * Create an instance of {@link FaxNumberType }
     * 
     */
    public FaxNumberType createFaxNumberType() {
        return new FaxNumberType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link EmployerType }
     * 
     */
    public EmployerType createEmployerType() {
        return new EmployerType();
    }

    /**
     * Create an instance of {@link AuditTrailType }
     * 
     */
    public AuditTrailType createAuditTrailType() {
        return new AuditTrailType();
    }

    /**
     * Create an instance of {@link EmailAddressContactPointUsageType }
     * 
     */
    public EmailAddressContactPointUsageType createEmailAddressContactPointUsageType() {
        return new EmailAddressContactPointUsageType();
    }

    /**
     * Create an instance of {@link ElectronicAddressType }
     * 
     */
    public ElectronicAddressType createElectronicAddressType() {
        return new ElectronicAddressType();
    }

    /**
     * Create an instance of {@link FatcaCRSType }
     * 
     */
    public FatcaCRSType createFatcaCRSType() {
        return new FatcaCRSType();
    }

    /**
     * Create an instance of {@link ElectronicAddressContactPointUsageType }
     * 
     */
    public ElectronicAddressContactPointUsageType createElectronicAddressContactPointUsageType() {
        return new ElectronicAddressContactPointUsageType();
    }

    /**
     * Create an instance of {@link EmployeeDisabilityType }
     * 
     */
    public EmployeeDisabilityType createEmployeeDisabilityType() {
        return new EmployeeDisabilityType();
    }

    /**
     * Create an instance of {@link OptInformationType }
     * 
     */
    public OptInformationType createOptInformationType() {
        return new OptInformationType();
    }

    /**
     * Create an instance of {@link PersonNameType }
     * 
     */
    public PersonNameType createPersonNameType() {
        return new PersonNameType();
    }

    /**
     * Create an instance of {@link FaxNumberContactPointUsageType }
     * 
     */
    public FaxNumberContactPointUsageType createFaxNumberContactPointUsageType() {
        return new FaxNumberContactPointUsageType();
    }

    /**
     * Create an instance of {@link MobilePhoneType }
     * 
     */
    public MobilePhoneType createMobilePhoneType() {
        return new MobilePhoneType();
    }

    /**
     * Create an instance of {@link LongTextsType }
     * 
     */
    public LongTextsType createLongTextsType() {
        return new LongTextsType();
    }

    /**
     * Create an instance of {@link PersonDemographicsType }
     * 
     */
    public PersonDemographicsType createPersonDemographicsType() {
        return new PersonDemographicsType();
    }

    /**
     * Create an instance of {@link OrganisationType }
     * 
     */
    public OrganisationType createOrganisationType() {
        return new OrganisationType();
    }

    /**
     * Create an instance of {@link PostalAddressType }
     * 
     */
    public PostalAddressType createPostalAddressType() {
        return new PostalAddressType();
    }

    /**
     * Create an instance of {@link EmployeeType }
     * 
     */
    public EmployeeType createEmployeeType() {
        return new EmployeeType();
    }

    /**
     * Create an instance of {@link OrganisationDemographicsType }
     * 
     */
    public OrganisationDemographicsType createOrganisationDemographicsType() {
        return new OrganisationDemographicsType();
    }

    /**
     * Create an instance of {@link PostalAddressContactPointUsageType }
     * 
     */
    public PostalAddressContactPointUsageType createPostalAddressContactPointUsageType() {
        return new PostalAddressContactPointUsageType();
    }

    /**
     * Create an instance of {@link TelephoneNumberType }
     * 
     */
    public TelephoneNumberType createTelephoneNumberType() {
        return new TelephoneNumberType();
    }

    /**
     * Create an instance of {@link PartyRegistrationType }
     * 
     */
    public PartyRegistrationType createPartyRegistrationType() {
        return new PartyRegistrationType();
    }

    /**
     * Create an instance of {@link RequestEnvelopeType }
     * 
     */
    public RequestEnvelopeType createRequestEnvelopeType() {
        return new RequestEnvelopeType();
    }

    /**
     * Create an instance of {@link EmailAddressType }
     * 
     */
    public EmailAddressType createEmailAddressType() {
        return new EmailAddressType();
    }

    /**
     * Create an instance of {@link TitlesType }
     * 
     */
    public TitlesType createTitlesType() {
        return new TitlesType();
    }

    /**
     * Create an instance of {@link TelephoneNumberContactPointUsageType }
     * 
     */
    public TelephoneNumberContactPointUsageType createTelephoneNumberContactPointUsageType() {
        return new TelephoneNumberContactPointUsageType();
    }

    /**
     * Create an instance of {@link MessageHeaderType }
     * 
     */
    public MessageHeaderType createMessageHeaderType() {
        return new MessageHeaderType();
    }

    /**
     * Create an instance of {@link ResultType }
     * 
     */
    public ResultType createResultType() {
        return new ResultType();
    }

    /**
     * Create an instance of {@link ConsumingEndpointType }
     * 
     */
    public ConsumingEndpointType createConsumingEndpointType() {
        return new ConsumingEndpointType();
    }

    /**
     * Create an instance of {@link ActionType }
     * 
     */
    public ActionType createActionType() {
        return new ActionType();
    }

    /**
     * Create an instance of {@link ErrorListType }
     * 
     */
    public ErrorListType createErrorListType() {
        return new ErrorListType();
    }

    /**
     * Create an instance of {@link DetailListType }
     * 
     */
    public DetailListType createDetailListType() {
        return new DetailListType();
    }

    /**
     * Create an instance of {@link DetailType }
     * 
     */
    public DetailType createDetailType() {
        return new DetailType();
    }

    /**
     * Create an instance of {@link TraceHeaderType }
     * 
     */
    public TraceHeaderType createTraceHeaderType() {
        return new TraceHeaderType();
    }

    /**
     * Create an instance of {@link ProducingEndpointType }
     * 
     */
    public ProducingEndpointType createProducingEndpointType() {
        return new ProducingEndpointType();
    }

    /**
     * Create an instance of {@link HeaderFieldType }
     * 
     */
    public HeaderFieldType createHeaderFieldType() {
        return new HeaderFieldType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link PropertiesType }
     * 
     */
    public PropertiesType createPropertiesType() {
        return new PropertiesType();
    }

    /**
     * Create an instance of {@link MessageDataType }
     * 
     */
    public MessageDataType createMessageDataType() {
        return new MessageDataType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link ServiceType }
     * 
     */
    public ServiceType createServiceType() {
        return new ServiceType();
    }

    /**
     * Create an instance of {@link HeaderPropertyType }
     * 
     */
    public HeaderPropertyType createHeaderPropertyType() {
        return new HeaderPropertyType();
    }

    /**
     * Create an instance of {@link TraceHeaderListType }
     * 
     */
    public TraceHeaderListType createTraceHeaderListType() {
        return new TraceHeaderListType();
    }

    /**
     * Create an instance of {@link ConnectionInfoType }
     * 
     */
    public ConnectionInfoType createConnectionInfoType() {
        return new ConnectionInfoType();
    }

    /**
     * Create an instance of {@link PartyType.Roles }
     * 
     */
    public PartyType.Roles createPartyTypeRoles() {
        return new PartyType.Roles();
    }

    /**
     * Create an instance of {@link BankDetailsType.BankDetailsInstance }
     * 
     */
    public BankDetailsType.BankDetailsInstance createBankDetailsTypeBankDetailsInstance() {
        return new BankDetailsType.BankDetailsInstance();
    }

    /**
     * Create an instance of {@link HandleBusinessPartnerResponseType.Party }
     * 
     */
    public HandleBusinessPartnerResponseType.Party createHandleBusinessPartnerResponseTypeParty() {
        return new HandleBusinessPartnerResponseType.Party();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HandleBusinessPartnerResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4", name = "HandleBusinessPartner_Response")
    public JAXBElement<HandleBusinessPartnerResponseType> createHandleBusinessPartnerResponse(HandleBusinessPartnerResponseType value) {
        return new JAXBElement<HandleBusinessPartnerResponseType>(_HandleBusinessPartnerResponse_QNAME, HandleBusinessPartnerResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageHeaderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nn.nl/XSD/Generic/MessageHeader/2", name = "MessageHeader")
    public JAXBElement<MessageHeaderType> createMessageHeader(MessageHeaderType value) {
        return new JAXBElement<MessageHeaderType>(_MessageHeader_QNAME, MessageHeaderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nn.nl/XSD/Generic/MessageHeader/2", name = "Result")
    public JAXBElement<ResultType> createResult(ResultType value) {
        return new JAXBElement<ResultType>(_Result_QNAME, ResultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HandleBusinessPartnerRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4", name = "HandleBusinessPartner_Request")
    public JAXBElement<HandleBusinessPartnerRequestType> createHandleBusinessPartnerRequest(HandleBusinessPartnerRequestType value) {
        return new JAXBElement<HandleBusinessPartnerRequestType>(_HandleBusinessPartnerRequest_QNAME, HandleBusinessPartnerRequestType.class, null, value);
    }

}
