//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.08 at 11:52:04 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.nn.dcdc.api.bpxsd;
