//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.08 at 11:52:04 AM CET 
//


package nl.nn.dcdc.api.bpxsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PartyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AuthorizationGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SourceSystem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Roles" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Role" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PartyType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PreferredLanguage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="Organisation" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}OrganisationType" minOccurs="0"/>
 *           &lt;element name="Person" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}PersonType" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="PartyRegistration" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}PartyRegistrationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PostalAddressContactPointUsage" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}PostalAddressContactPointUsageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TelephoneNumberContactPointUsage" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}TelephoneNumberContactPointUsageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MobilePhoneContactPointUsage" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}MobilePhoneContactPointUsageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FaxNumberContactPointUsage" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}FaxNumberContactPointUsageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EmailAddressContactPointUsage" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}EmailAddressContactPointUsageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ElectronicAddressContactPointUsage" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}ElectronicAddressContactPointUsageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PreferredCommunicationMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OptInformation" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}OptInformationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FatcaCRS" type="{http://nn.nl/XSD/CustomerAdministration/Party/2/HandleBusinessPartner/4}FatcaCRSType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartyType", propOrder = {
    "id",
    "authorizationGroup",
    "sourceSystem",
    "roles",
    "partyType",
    "preferredLanguage",
    "organisation",
    "person",
    "partyRegistration",
    "postalAddressContactPointUsage",
    "telephoneNumberContactPointUsage",
    "mobilePhoneContactPointUsage",
    "faxNumberContactPointUsage",
    "emailAddressContactPointUsage",
    "electronicAddressContactPointUsage",
    "preferredCommunicationMethod",
    "optInformation",
    "fatcaCRS"
})
public class PartyType {

    @XmlElement(name = "Id")
    protected String id;
    @XmlElement(name = "AuthorizationGroup")
    protected String authorizationGroup;
    @XmlElement(name = "SourceSystem")
    protected String sourceSystem;
    @XmlElement(name = "Roles")
    protected List<PartyType.Roles> roles;
    @XmlElement(name = "PartyType")
    protected String partyType;
    @XmlElement(name = "PreferredLanguage")
    protected String preferredLanguage;
    @XmlElement(name = "Organisation")
    protected OrganisationType organisation;
    @XmlElement(name = "Person")
    protected PersonType person;
    @XmlElement(name = "PartyRegistration")
    protected List<PartyRegistrationType> partyRegistration;
    @XmlElement(name = "PostalAddressContactPointUsage")
    protected List<PostalAddressContactPointUsageType> postalAddressContactPointUsage;
    @XmlElement(name = "TelephoneNumberContactPointUsage")
    protected List<TelephoneNumberContactPointUsageType> telephoneNumberContactPointUsage;
    @XmlElement(name = "MobilePhoneContactPointUsage")
    protected List<MobilePhoneContactPointUsageType> mobilePhoneContactPointUsage;
    @XmlElement(name = "FaxNumberContactPointUsage")
    protected List<FaxNumberContactPointUsageType> faxNumberContactPointUsage;
    @XmlElement(name = "EmailAddressContactPointUsage")
    protected List<EmailAddressContactPointUsageType> emailAddressContactPointUsage;
    @XmlElement(name = "ElectronicAddressContactPointUsage")
    protected List<ElectronicAddressContactPointUsageType> electronicAddressContactPointUsage;
    @XmlElement(name = "PreferredCommunicationMethod")
    protected String preferredCommunicationMethod;
    @XmlElement(name = "OptInformation")
    protected List<OptInformationType> optInformation;
    @XmlElement(name = "FatcaCRS")
    protected List<FatcaCRSType> fatcaCRS;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the authorizationGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizationGroup() {
        return authorizationGroup;
    }

    /**
     * Sets the value of the authorizationGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizationGroup(String value) {
        this.authorizationGroup = value;
    }

    /**
     * Gets the value of the sourceSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceSystem() {
        return sourceSystem;
    }

    /**
     * Sets the value of the sourceSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceSystem(String value) {
        this.sourceSystem = value;
    }

    /**
     * Gets the value of the roles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyType.Roles }
     * 
     * 
     */
    public List<PartyType.Roles> getRoles() {
        if (roles == null) {
            roles = new ArrayList<PartyType.Roles>();
        }
        return this.roles;
    }

    /**
     * Gets the value of the partyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyType() {
        return partyType;
    }

    /**
     * Sets the value of the partyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyType(String value) {
        this.partyType = value;
    }

    /**
     * Gets the value of the preferredLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredLanguage() {
        return preferredLanguage;
    }

    /**
     * Sets the value of the preferredLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredLanguage(String value) {
        this.preferredLanguage = value;
    }

    /**
     * Gets the value of the organisation property.
     * 
     * @return
     *     possible object is
     *     {@link OrganisationType }
     *     
     */
    public OrganisationType getOrganisation() {
        return organisation;
    }

    /**
     * Sets the value of the organisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganisationType }
     *     
     */
    public void setOrganisation(OrganisationType value) {
        this.organisation = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link PersonType }
     *     
     */
    public PersonType getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonType }
     *     
     */
    public void setPerson(PersonType value) {
        this.person = value;
    }

    /**
     * Gets the value of the partyRegistration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyRegistration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyRegistration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyRegistrationType }
     * 
     * 
     */
    public List<PartyRegistrationType> getPartyRegistration() {
        if (partyRegistration == null) {
            partyRegistration = new ArrayList<PartyRegistrationType>();
        }
        return this.partyRegistration;
    }

    /**
     * Gets the value of the postalAddressContactPointUsage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the postalAddressContactPointUsage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPostalAddressContactPointUsage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PostalAddressContactPointUsageType }
     * 
     * 
     */
    public List<PostalAddressContactPointUsageType> getPostalAddressContactPointUsage() {
        if (postalAddressContactPointUsage == null) {
            postalAddressContactPointUsage = new ArrayList<PostalAddressContactPointUsageType>();
        }
        return this.postalAddressContactPointUsage;
    }

    /**
     * Gets the value of the telephoneNumberContactPointUsage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the telephoneNumberContactPointUsage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTelephoneNumberContactPointUsage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TelephoneNumberContactPointUsageType }
     * 
     * 
     */
    public List<TelephoneNumberContactPointUsageType> getTelephoneNumberContactPointUsage() {
        if (telephoneNumberContactPointUsage == null) {
            telephoneNumberContactPointUsage = new ArrayList<TelephoneNumberContactPointUsageType>();
        }
        return this.telephoneNumberContactPointUsage;
    }

    /**
     * Gets the value of the mobilePhoneContactPointUsage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mobilePhoneContactPointUsage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMobilePhoneContactPointUsage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MobilePhoneContactPointUsageType }
     * 
     * 
     */
    public List<MobilePhoneContactPointUsageType> getMobilePhoneContactPointUsage() {
        if (mobilePhoneContactPointUsage == null) {
            mobilePhoneContactPointUsage = new ArrayList<MobilePhoneContactPointUsageType>();
        }
        return this.mobilePhoneContactPointUsage;
    }

    /**
     * Gets the value of the faxNumberContactPointUsage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the faxNumberContactPointUsage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFaxNumberContactPointUsage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FaxNumberContactPointUsageType }
     * 
     * 
     */
    public List<FaxNumberContactPointUsageType> getFaxNumberContactPointUsage() {
        if (faxNumberContactPointUsage == null) {
            faxNumberContactPointUsage = new ArrayList<FaxNumberContactPointUsageType>();
        }
        return this.faxNumberContactPointUsage;
    }

    /**
     * Gets the value of the emailAddressContactPointUsage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the emailAddressContactPointUsage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmailAddressContactPointUsage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EmailAddressContactPointUsageType }
     * 
     * 
     */
    public List<EmailAddressContactPointUsageType> getEmailAddressContactPointUsage() {
        if (emailAddressContactPointUsage == null) {
            emailAddressContactPointUsage = new ArrayList<EmailAddressContactPointUsageType>();
        }
        return this.emailAddressContactPointUsage;
    }

    /**
     * Gets the value of the electronicAddressContactPointUsage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the electronicAddressContactPointUsage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElectronicAddressContactPointUsage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ElectronicAddressContactPointUsageType }
     * 
     * 
     */
    public List<ElectronicAddressContactPointUsageType> getElectronicAddressContactPointUsage() {
        if (electronicAddressContactPointUsage == null) {
            electronicAddressContactPointUsage = new ArrayList<ElectronicAddressContactPointUsageType>();
        }
        return this.electronicAddressContactPointUsage;
    }

    /**
     * Gets the value of the preferredCommunicationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredCommunicationMethod() {
        return preferredCommunicationMethod;
    }

    /**
     * Sets the value of the preferredCommunicationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredCommunicationMethod(String value) {
        this.preferredCommunicationMethod = value;
    }

    /**
     * Gets the value of the optInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the optInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OptInformationType }
     * 
     * 
     */
    public List<OptInformationType> getOptInformation() {
        if (optInformation == null) {
            optInformation = new ArrayList<OptInformationType>();
        }
        return this.optInformation;
    }

    /**
     * Gets the value of the fatcaCRS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fatcaCRS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFatcaCRS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FatcaCRSType }
     * 
     * 
     */
    public List<FatcaCRSType> getFatcaCRS() {
        if (fatcaCRS == null) {
            fatcaCRS = new ArrayList<FatcaCRSType>();
        }
        return this.fatcaCRS;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Role" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "role",
        "startDate",
        "endDate"
    })
    public static class Roles {

        @XmlElement(name = "Role")
        protected String role;
        @XmlElement(name = "StartDate")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar startDate;
        @XmlElement(name = "EndDate")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar endDate;

        /**
         * Gets the value of the role property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRole() {
            return role;
        }

        /**
         * Sets the value of the role property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRole(String value) {
            this.role = value;
        }

        /**
         * Gets the value of the startDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStartDate() {
            return startDate;
        }

        /**
         * Sets the value of the startDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStartDate(XMLGregorianCalendar value) {
            this.startDate = value;
        }

        /**
         * Gets the value of the endDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEndDate() {
            return endDate;
        }

        /**
         * Sets the value of the endDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEndDate(XMLGregorianCalendar value) {
            this.endDate = value;
        }

    }

}
