//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.08 at 11:52:04 AM CET 
//


package nl.nn.dcdc.api.bpxsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TraceHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TraceHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Sender" type="{http://nn.nl/XSD/Generic/MessageHeader/2}ProducingEndpointType"/>
 *         &lt;element name="Receiver" type="{http://nn.nl/XSD/Generic/MessageHeader/2}ConsumingEndpointType"/>
 *         &lt;element name="Service" type="{http://nn.nl/XSD/Generic/MessageHeader/2}ServiceType"/>
 *         &lt;element name="MessageData" type="{http://nn.nl/XSD/Generic/MessageHeader/2}MessageDataType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TraceHeaderType", namespace = "http://nn.nl/XSD/Generic/MessageHeader/2", propOrder = {
    "sender",
    "receiver",
    "service",
    "messageData"
})
public class TraceHeaderType {

    @XmlElement(name = "Sender", required = true)
    protected ProducingEndpointType sender;
    @XmlElement(name = "Receiver", required = true)
    protected ConsumingEndpointType receiver;
    @XmlElement(name = "Service", required = true)
    protected ServiceType service;
    @XmlElement(name = "MessageData", required = true)
    protected MessageDataType messageData;

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link ProducingEndpointType }
     *     
     */
    public ProducingEndpointType getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProducingEndpointType }
     *     
     */
    public void setSender(ProducingEndpointType value) {
        this.sender = value;
    }

    /**
     * Gets the value of the receiver property.
     * 
     * @return
     *     possible object is
     *     {@link ConsumingEndpointType }
     *     
     */
    public ConsumingEndpointType getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsumingEndpointType }
     *     
     */
    public void setReceiver(ConsumingEndpointType value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceType }
     *     
     */
    public ServiceType getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceType }
     *     
     */
    public void setService(ServiceType value) {
        this.service = value;
    }

    /**
     * Gets the value of the messageData property.
     * 
     * @return
     *     possible object is
     *     {@link MessageDataType }
     *     
     */
    public MessageDataType getMessageData() {
        return messageData;
    }

    /**
     * Sets the value of the messageData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageDataType }
     *     
     */
    public void setMessageData(MessageDataType value) {
        this.messageData = value;
    }

}
